/**
 * USDExporter.js
 *
 * Export cognitive profiles as Universal Scene Description (USDA) format.
 *
 * THESIS: USD composition semantics (LIVRPS) map to cognitive priority.
 * This is not scene description — it's AGENT STATE DESCRIPTION.
 *
 * The exported profile is designed to:
 * 1. Reference the base CognitiveSubstrate in CLAUDE.md
 * 2. Override default values via USD composition
 * 3. Be verifiable via checksum
 * 4. Be human-readable AND machine-parseable
 *
 * LIVRPS Priority (how USD merges opinions):
 * - Local opinions (conversation context) — highest
 * - Inherit from parent prims
 * - Variants for mode switching
 * - References to external assets ← TranslatorsProfile uses this
 * - Payloads for deferred loading
 * - Specialize for inheritance
 */

import { DIMENSION_CONFIG, DeterministicProfileEngine } from './DeterministicProfileEngine.js';
import { VERSION } from '../config/version.js';
import { renderProfileAsText, COGNITIVE_DOMAINS } from '../calibration/index.js';

export class USDExporter {
  /**
   * Export profile as USDA (ASCII USD format)
   *
   * @param {Object} profile - Complete profile from DeterministicProfileEngine
   * @param {Object} options - Export options
   * @returns {string} Valid USDA content
   */
  static toUSDA(profile, options = {}) {
    // Validate profile before export
    const validation = DeterministicProfileEngine.validateProfile(profile);
    if (!validation.valid) {
      throw new Error(`Invalid profile: ${validation.errors.join(', ')}`);
    }

    const {
      includeRaw = false,
      referencePath = '/CognitiveSubstrate/Profile',
      indent = '  '
    } = options;

    const timestamp = new Date().toISOString();

    let usda = `#usda 1.0
(
    defaultPrim = "TranslatorsProfile"
    doc = "Cognitive profile generated by The Translators interview game"
    customLayerData = {
        string generator = "The Translators v${profile.version || VERSION.profile}"
        string checksum = "${profile.checksum}"
        string anchor = "${profile.anchor}"
        string generated = "${timestamp}"
        string thesis = "USD as Universal State Description"
    }
)

def "TranslatorsProfile" (
    references = @${referencePath}@
    doc = "Behavioral preferences derived from cognitive interview — overrides base profile"
    kind = "component"
)
{
${this.formatTraits(profile.traits, indent)}

${this.formatInsights(profile.insights, indent)}

${this.formatSignalPriority(profile.traits, indent)}
}
`;

    if (includeRaw) {
      usda += this.formatRawAnswers(profile.raw, indent);
    }

    return usda;
  }

  /**
   * Format traits as USD custom attributes
   */
  static formatTraits(traits, indent = '  ') {
    const sortedDims = Object.keys(traits).sort();
    const lines = [`${indent}# === COGNITIVE TRAITS ===`];

    sortedDims.forEach(dim => {
      const trait = traits[dim];
      lines.push(`${indent}# ${dim.charAt(0).toUpperCase() + dim.slice(1)}`);
      lines.push(`${indent}custom string ${dim} = "${trait.label}"`);
      lines.push(`${indent}custom float ${dim}:score = ${trait.value.toFixed(2)}`);
      lines.push(`${indent}custom string ${dim}:behavior = "${this.escapeString(trait.behavior)}"`);
      lines.push('');
    });

    return lines.join('\n');
  }

  /**
   * Format insights as USD custom attributes
   */
  static formatInsights(insights, indent = '  ') {
    const lines = [`${indent}# === COMMUNICATION INSIGHTS ===`];
    lines.push(`${indent}custom string[] insights = [`);

    insights.forEach((insight, i) => {
      const comma = i < insights.length - 1 ? ',' : '';
      lines.push(`${indent}${indent}"${this.escapeString(insight)}"${comma}`);
    });

    lines.push(`${indent}]`);
    return lines.join('\n');
  }

  /**
   * Format signal priority rules for AI consumption
   * These map traits to behavioral adjustments
   */
  static formatSignalPriority(traits, indent = '  ') {
    const lines = [`${indent}# === SIGNAL PRIORITY ===`];
    lines.push(`${indent}# Apply in order: emotional_state > mode_switch > domain > task_type`);
    lines.push(`${indent}custom string[] signal_overrides = [`);

    const sortedDims = Object.keys(traits).sort();
    sortedDims.forEach((dim, i) => {
      const trait = traits[dim];
      const signal = this.traitToSignal(dim, trait);
      const comma = i < sortedDims.length - 1 ? ',' : '';
      lines.push(`${indent}${indent}"${signal}"${comma}`);
    });

    lines.push(`${indent}]`);
    return lines.join('\n');
  }

  /**
   * Convert trait to signal instruction
   */
  static traitToSignal(dimension, trait) {
    const signals = {
      pace: trait.value > 0.6 ? 'pace:deliberate → provide context before conclusions'
        : trait.value < 0.4 ? 'pace:quick → lead with the answer'
          : 'pace:adaptive → match user energy',

      thoroughness: trait.value > 0.6 ? 'detail:high → include comprehensive information'
        : trait.value < 0.4 ? 'detail:minimal → start sparse, expand on request'
          : 'detail:balanced → appropriate depth for context',

      organization: trait.value > 0.6 ? 'structure:ordered → use lists, steps, hierarchy'
        : trait.value < 0.4 ? 'structure:narrative → use stories and examples'
          : 'structure:mixed → blend as appropriate',

      exploration: trait.value > 0.6 ? 'tangents:embrace → follow interesting threads'
        : trait.value < 0.4 ? 'tangents:redirect → stay on topic'
          : 'tangents:selective → follow good ones',

      communication: trait.value > 0.6 ? 'feedback:gentle → encourage while correcting'
        : trait.value < 0.4 ? 'feedback:direct → tell it straight'
          : 'feedback:contextual → match situation',

      ambiguity: trait.value > 0.6 ? 'uncertainty:explore → present possibilities'
        : trait.value < 0.4 ? 'uncertainty:clarify → be direct about unknowns'
          : 'uncertainty:balanced → honest assessment',

      rhythm: trait.value > 0.6 ? 'pauses:embrace → silence is productive'
        : trait.value < 0.4 ? 'pauses:minimize → keep momentum'
          : 'pauses:natural → comfortable flow',

      tangents: trait.value > 0.6 ? 'divergence:welcome → insights live in tangents'
        : trait.value < 0.4 ? 'divergence:limit → bring back on track'
          : 'divergence:curated → follow interesting ones'
    };

    return signals[dimension] || `${dimension}:${trait.label.toLowerCase()}`;
  }

  /**
   * Format raw answers for debugging/transparency
   */
  static formatRawAnswers(raw, indent = '  ') {
    if (!raw || Object.keys(raw).length === 0) return '';

    const lines = ['\ndef "RawAnswers" ('];
    lines.push(`${indent}doc = "Original interview responses for transparency"`);
    lines.push(')');
    lines.push('{');

    Object.entries(raw).forEach(([questionId, answer]) => {
      lines.push(`${indent}custom string ${questionId} = "${answer.value}"`);
      lines.push(`${indent}custom float ${questionId}:trait = ${answer.trait}`);
      lines.push(`${indent}custom int ${questionId}:depth = ${answer.depth}`);
    });

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Escape string for USD (handle quotes, newlines)
   */
  static escapeString(str) {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/'/g, "\\'");
  }

  /**
   * Export as compact JSON-LD with USD context
   * Alternative format for web consumption
   */
  static toJSONLD(profile) {
    // Validate profile before export
    const validation = DeterministicProfileEngine.validateProfile(profile);
    if (!validation.valid) {
      throw new Error(`Invalid profile: ${validation.errors.join(', ')}`);
    }

    return {
      '@context': {
        '@vocab': 'https://josephibrahim.com/translators/v1/',
        'usd': 'https://openusd.org/ns/',
        'traits': '@nest',
        'insights': '@list'
      },
      '@type': 'CognitiveProfile',
      '@id': `translators:profile:${profile.checksum}`,
      'usd:defaultPrim': 'TranslatorsProfile',
      'generator': VERSION.generator,
      'version': profile.version || VERSION.profile,
      'checksum': profile.checksum,
      'anchor': profile.anchor,
      'traits': Object.entries(profile.traits).reduce((acc, [dim, trait]) => {
        acc[dim] = {
          '@type': 'CognitiveTrait',
          'label': trait.label,
          'score': trait.value,
          'behavior': trait.behavior
        };
        return acc;
      }, {}),
      'insights': profile.insights
    };
  }

  /**
   * Export as Markdown with embedded USD
   * Best format for CLAUDE.md integration
   */
  static toMarkdown(profile, options = {}) {
    // Validate profile before export
    const validation = DeterministicProfileEngine.validateProfile(profile);
    if (!validation.valid) {
      throw new Error(`Invalid profile: ${validation.errors.join(', ')}`);
    }

    const {
      includeUSDA = true,
      title = 'Cognitive Profile'
    } = options;

    let md = `${profile.anchor}

# ${title}

*Generated by The Translators — a cognitive interview*

## Communication Preferences

| Dimension | Preference | Score | Behavior |
|-----------|------------|-------|----------|
`;

    const sortedDims = Object.keys(profile.traits).sort();
    sortedDims.forEach(dim => {
      const trait = profile.traits[dim];
      const dimTitle = dim.charAt(0).toUpperCase() + dim.slice(1);
      md += `| ${dimTitle} | ${trait.label} | ${trait.value.toFixed(2)} | ${trait.behavior} |\n`;
    });

    md += `
## Key Insights

`;
    profile.insights.forEach((insight, i) => {
      md += `${i + 1}. ${insight}\n`;
    });

    md += `
## Integrity

- **Checksum**: \`${profile.checksum}\`
- **Anchor**: \`${profile.anchor}\`
- **Version**: ${profile.version || VERSION.profile}

> To verify integrity: Same 8 answers will always produce checksum \`${profile.checksum}\`
`;

    if (includeUSDA) {
      md += `
## USD Format

\`\`\`usda
${this.toUSDA(profile)}
\`\`\`
`;
    }

    return md;
  }

  /**
   * Generate CLAUDE.md integration snippet
   * Ready to paste into the Cognitive Substrate section
   */
  static toClaudeIntegration(profile) {
    return `
<!-- TRANSLATORS PROFILE INTEGRATION -->
<!-- Generated: ${new Date().toISOString()} -->
<!-- Checksum: ${profile.checksum} -->

Add this to your CLAUDE.md Cognitive Substrate:

\`\`\`usda
def "TranslatorsProfile" (
    references = @/CognitiveSubstrate/Profile@
    doc = "Override profile from The Translators interview"
)
{
${this.formatTraits(profile.traits, '    ').trim()}
}
\`\`\`

Or add this anchor to conversation context:

\`\`\`
${profile.anchor}
\`\`\`
`;
  }

  // ============================================================================
  // COGNITIVE PROFILE EXPORT
  // ============================================================================

  /**
   * Export cognitive profile as USDA format
   * Compatible with CLAUDE.md Cognitive Substrate
   *
   * @param {Object} cognitiveProfile - Cognitive profile from CognitiveCalibrationManager
   * @param {Object} options - Export options
   * @returns {string} Valid USDA content
   */
  static toCognitiveUSDA(cognitiveProfile, options = {}) {
    if (!cognitiveProfile) {
      throw new Error('No cognitive profile provided');
    }

    const {
      includeRaw = true,
      referencePath = '/CognitiveSubstrate/CognitiveProfile',
      indent = '  '
    } = options;

    const timestamp = new Date().toISOString();
    const checksum = cognitiveProfile.profileChecksum || 'unknown';

    let usda = `#usda 1.0
(
    defaultPrim = "CognitiveProfile"
    doc = "Deep cognitive profile generated by The Translators calibration system"
    customLayerData = {
        string generator = "The Translators Cognitive Calibration v${VERSION.profile}"
        string checksum = "${checksum}"
        string generated = "${timestamp}"
        string thesis = "USD as Universal State Description for Cognitive Architecture"
        int questionsAnswered = ${cognitiveProfile.questionsAnswered || 0}
        int sessionsCompleted = ${cognitiveProfile.sessionsCompleted || 0}
    }
)

def "CognitiveProfile" (
    references = @${referencePath}@
    doc = "Behavioral and cognitive patterns derived from deep profiling"
    kind = "component"
)
{
`;

    // Format each cognitive domain
    usda += this.formatCognitiveDomains(cognitiveProfile, indent);

    // Format emergent patterns
    usda += this.formatEmergentPatterns(cognitiveProfile, indent);

    usda += '}\n';

    // Add raw behavioral data if requested
    if (includeRaw && cognitiveProfile.behavioralSignals) {
      usda += this.formatBehavioralSignals(cognitiveProfile.behavioralSignals, indent);
    }

    return usda;
  }

  /**
   * Format cognitive domains as USD attributes
   */
  static formatCognitiveDomains(profile, indent = '  ') {
    const domains = ['attention', 'workingMemory', 'timePerception', 'energy',
                     'motivation', 'processing', 'emotional', 'social'];
    const lines = [`${indent}# === COGNITIVE DOMAINS ===\n`];

    for (const domain of domains) {
      const data = profile[domain];
      if (!data || Object.keys(data).length === 0) continue;

      lines.push(`${indent}# ${domain.charAt(0).toUpperCase() + domain.slice(1)}`);
      lines.push(`${indent}def "${domain}" (`);
      lines.push(`${indent}${indent}doc = "Cognitive domain: ${domain}"`);
      lines.push(`${indent})`);
      lines.push(`${indent}{`);

      // Format each attribute in the domain
      for (const [key, value] of Object.entries(data)) {
        if (value === null || value === undefined) continue;

        const attrName = key.replace(/([A-Z])/g, '_$1').toLowerCase();

        if (typeof value === 'number') {
          lines.push(`${indent}${indent}custom float ${attrName} = ${value.toFixed(3)}`);
        } else if (typeof value === 'boolean') {
          lines.push(`${indent}${indent}custom bool ${attrName} = ${value}`);
        } else if (Array.isArray(value)) {
          const arrayStr = value.map(v => `"${this.escapeString(String(v))}"`).join(', ');
          lines.push(`${indent}${indent}custom string[] ${attrName} = [${arrayStr}]`);
        } else {
          lines.push(`${indent}${indent}custom string ${attrName} = "${this.escapeString(String(value))}"`);
        }
      }

      lines.push(`${indent}}`);
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Format emergent patterns as USD attributes
   */
  static formatEmergentPatterns(profile, indent = '  ') {
    const patterns = profile.emergentPatterns;
    if (!patterns) return '';

    const lines = [`\n${indent}# === EMERGENT PATTERNS ===`];
    lines.push(`${indent}def "EmergentPatterns" (`);
    lines.push(`${indent}${indent}doc = "Cross-domain patterns detected from triangulated data"`);
    lines.push(`${indent})`);
    lines.push(`${indent}{`);

    for (const [key, value] of Object.entries(patterns)) {
      if (value === null || value === undefined || value === 0) continue;

      const attrName = key.replace(/([A-Z])/g, '_$1').toLowerCase();
      if (typeof value === 'number') {
        lines.push(`${indent}${indent}custom float ${attrName} = ${value.toFixed(3)}`);

        // Add human-readable label for significant patterns
        if (value > 0.5) {
          const labels = {
            interestDrivenNervousSystem: 'Interest-driven activation pattern detected',
            executiveFunctionChallenges: 'Executive function differences present',
            rejectionSensitivity: 'Heightened rejection sensitivity indicated'
          };
          if (labels[key]) {
            lines.push(`${indent}${indent}custom string ${attrName}:label = "${labels[key]}"`);
          }
        }
      }
    }

    lines.push(`${indent}}`);
    return lines.join('\n') + '\n';
  }

  /**
   * Format behavioral signals for transparency
   */
  static formatBehavioralSignals(signals, indent = '  ') {
    if (!signals || Object.keys(signals).length === 0) return '';

    const lines = ['\ndef "BehavioralSignals" ('];
    lines.push(`${indent}doc = "Implicit behavioral data captured during calibration"`);
    lines.push(')');
    lines.push('{');

    const signalTypes = ['responseTimeVariability', 'revisionCount', 'engagementPattern'];
    for (const type of signalTypes) {
      if (signals[type] !== undefined) {
        if (typeof signals[type] === 'number') {
          lines.push(`${indent}custom float ${type} = ${signals[type].toFixed(3)}`);
        } else {
          lines.push(`${indent}custom string ${type} = "${this.escapeString(String(signals[type]))}"`);
        }
      }
    }

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Export cognitive profile as JSON-LD format
   * Semantic web compatible
   */
  static toCognitiveJSONLD(cognitiveProfile) {
    if (!cognitiveProfile) {
      throw new Error('No cognitive profile provided');
    }

    const checksum = cognitiveProfile.profileChecksum || 'unknown';

    return {
      '@context': {
        '@vocab': 'https://josephibrahim.com/translators/cognitive/v1/',
        'usd': 'https://openusd.org/ns/',
        'schema': 'https://schema.org/',
        'cognitive': '@nest',
        'emergent': '@nest'
      },
      '@type': 'CognitiveProfile',
      '@id': `translators:cognitive:${checksum}`,
      'usd:defaultPrim': 'CognitiveProfile',
      'generator': `The Translators Cognitive Calibration v${VERSION.profile}`,
      'generated': new Date().toISOString(),
      'checksum': checksum,
      'questionsAnswered': cognitiveProfile.questionsAnswered || 0,
      'sessionsCompleted': cognitiveProfile.sessionsCompleted || 0,
      'cognitive': {
        attention: this.formatDomainForJSON(cognitiveProfile.attention),
        workingMemory: this.formatDomainForJSON(cognitiveProfile.workingMemory),
        timePerception: this.formatDomainForJSON(cognitiveProfile.timePerception),
        energy: this.formatDomainForJSON(cognitiveProfile.energy),
        motivation: this.formatDomainForJSON(cognitiveProfile.motivation),
        processing: this.formatDomainForJSON(cognitiveProfile.processing),
        emotional: this.formatDomainForJSON(cognitiveProfile.emotional),
        social: this.formatDomainForJSON(cognitiveProfile.social)
      },
      'emergent': cognitiveProfile.emergentPatterns || {}
    };
  }

  /**
   * Format domain data for JSON (filter nulls/zeros)
   */
  static formatDomainForJSON(domain) {
    if (!domain) return {};
    const result = {};
    for (const [key, value] of Object.entries(domain)) {
      if (value !== null && value !== undefined && value !== 0 && value !== '') {
        result[key] = value;
      }
    }
    return result;
  }

  /**
   * Export cognitive profile as Markdown with USD
   */
  static toCognitiveMarkdown(cognitiveProfile, options = {}) {
    if (!cognitiveProfile) {
      throw new Error('No cognitive profile provided');
    }

    const {
      includeUSDA = true,
      title = 'Cognitive Profile'
    } = options;

    const checksum = cognitiveProfile.profileChecksum || 'unknown';

    let md = `# ${title}

*Generated by The Translators — Deep Cognitive Calibration*

---

`;

    // Use the text renderer for human-readable output
    try {
      md += renderProfileAsText(cognitiveProfile);
    } catch (e) {
      md += `*Profile rendering unavailable: ${e.message}*\n\n`;
    }

    md += `
---

## Metadata

- **Checksum**: \`${checksum}\`
- **Questions Answered**: ${cognitiveProfile.questionsAnswered || 0}
- **Sessions Completed**: ${cognitiveProfile.sessionsCompleted || 0}
- **Last Updated**: ${cognitiveProfile.lastUpdated ? new Date(cognitiveProfile.lastUpdated).toLocaleDateString() : 'Unknown'}

`;

    if (includeUSDA) {
      md += `
## USD Format

\`\`\`usda
${this.toCognitiveUSDA(cognitiveProfile, { includeRaw: false })}
\`\`\`
`;
    }

    return md;
  }

  /**
   * Export combined profile (legacy traits + cognitive) for full integration
   */
  static toFullProfile(profile, options = {}) {
    let md = this.toMarkdown(profile, { ...options, includeUSDA: false });

    if (profile.cognitive) {
      md += '\n\n---\n\n';
      md += '# Deep Cognitive Insights\n\n';
      md += this.toCognitiveMarkdown(profile.cognitive, { includeUSDA: false });
    }

    if (options.includeUSDA) {
      md += '\n\n## Combined USD Export\n\n';
      md += '```usda\n';
      md += this.toUSDA(profile, { includeRaw: false });
      if (profile.cognitive) {
        md += '\n\n# Cognitive Layer\n';
        md += this.toCognitiveUSDA(profile.cognitive, { includeRaw: false });
      }
      md += '\n```\n';
    }

    return md;
  }
}
